## Chapter 2 -  End-to-End Machine Learning Project
## Feature Engineering 

Input: Raw data

Output: Data after preprocessing & feature engineering

In [1]:
import pickle

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (LabelEncoder, OneHotEncoder, LabelBinarizer, StandardScaler)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, FeatureUnion

### Ingest

In [2]:
df = pd.read_csv('housing.csv')
print(df.shape)

df_features = df.drop(['median_house_value'], axis=1).copy()
df_target = df[['median_house_value']].copy()

df_numericonly = df_features.drop(['ocean_proximity'], axis=1).copy()
NUMERIC_COLUMNS = list(df_numericonly)
df_categoricalonly = df_features[['ocean_proximity']].copy()
CATEGORICAL_COLUMNS = list(df_categoricalonly)

(20640, 10)


In [3]:
# For testing
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

### Feature Engineering Pipeline

In [4]:
# Prepare pipelines

class MyLabelBinarizer(TransformerMixin):
    '''
        Used for the pipeline as the vanilla LabelBinarizer does not have the transform() function
        for 3 params
    '''
    
    def __init__(self, *args, **kwargs):
        self.encoder = LabelBinarizer(*args, **kwargs)
        
    def fit(self, x, y=0):
        self.encoder.fit(x)
        return self
    
    def transform(self, x, y=0):
        return self.encoder.transform(x)

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    _add_bedrooms_per_room = True
    _rooms_ix, _bedrooms_ix, _population_ix, _household_ix = 3,4,5,6
    
    def __init__(self):
        pass
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        rooms_per_household = X[:, self._rooms_ix]/X[:, self._household_ix]
        population_per_household = X[:, self._population_ix]/X[:, self._household_ix]
        if self._add_bedrooms_per_room:
            bedrooms_per_room = X[:, self._bedrooms_ix]/X[:, self._rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X,rooms_per_household, population_per_household]

numerical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler())])   

full_pipeline = ColumnTransformer([
    ('num_pipeline', numerical_pipeline, NUMERIC_COLUMNS),
    ('one_hot_encoder', OneHotEncoder(), CATEGORICAL_COLUMNS),])

In [5]:
# Test pipelines

# print(df_numericonly.head(3).shape)
# numerical_smoketest = numerical_pipeline.fit_transform(df_numericonly.head(3))
# print(numerical_smoketest)
# print(numerical_smoketest.shape)
# print()

# print(df.head(3).shape)
# full_smoketest = full_pipeline.fit_transform(df.head(3))
# print(full_smoketest)
# print(full_smoketest.shape) # only 1 category so only 12 columns
# print()

# print(np.array(df.head(3).values))
# values_out = full_pipeline.fit_transform(df.head(3))
# print(values_out[:3])
# print(values_out.shape)

In [6]:
columns_out = (list(df_numericonly) + 
               ['rooms per_household', 'population_per_household', 'bedrooms_per_room'] + 
               ['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'])
print(columns_out)
print(len(columns_out))

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'rooms per_household', 'population_per_household', 'bedrooms_per_room', '<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN']
16


In [7]:
values_out = full_pipeline.fit_transform(df)
print(values_out.shape)
print(values_out[:3])

(20640, 16)
[[-1.32783522  1.05254828  0.98214266 -0.8048191  -0.97247648 -0.9744286
  -0.97703285  2.34476576  0.62855945 -0.04959654 -1.02998783  0.
   0.          0.          1.          0.        ]
 [-1.32284391  1.04318455 -0.60701891  2.0458901   1.35714343  0.86143887
   1.66996103  2.33223796  0.32704136 -0.09251223 -0.8888972   0.
   0.          0.          1.          0.        ]
 [-1.33282653  1.03850269  1.85618152 -0.53574589 -0.82702426 -0.82077735
  -0.84363692  1.7826994   1.15562047 -0.02584253 -1.29168566  0.
   0.          0.          1.          0.        ]]


In [8]:
df_out = pd.DataFrame(values_out, columns=columns_out)
display(df_out.head())

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0  -1.327835  1.052548            0.982143    -0.804819       -0.972476   
1  -1.322844  1.043185           -0.607019     2.045890        1.357143   
2  -1.332827  1.038503            1.856182    -0.535746       -0.827024   
3  -1.337818  1.038503            1.856182    -0.624215       -0.719723   
4  -1.337818  1.038503            1.856182    -0.462404       -0.612423   

   population  households  median_income  rooms per_household  \
0   -0.974429   -0.977033       2.344766             0.628559   
1    0.861439    1.669961       2.332238             0.327041   
2   -0.820777   -0.843637       1.782699             1.155620   
3   -0.766028   -0.733781       0.932968             0.156966   
4   -0.759847   -0.629157      -0.012881             0.344711   

   population_per_household  bedrooms_per_room  <1H OCEAN  INLAND  ISLAND  \
0                 -0.049597          -1.029988        0.0     0.0     0.0   
1                 -0.092512          -0.888897        0.0     0.0     0.0   
2                 -0.025843          -1.291686        0.0     0.0     0.0   
3                 -0.050329          -0.449613        0.0     0.0     0.0   
4                 -0.085616          -0.639087        0.0     0.0     0.0   

   NEAR BAY  NEAR OCEAN  
0       1.0         0.0  
1       1.0         0.0  
2       1.0         0.0  
3       1.0         0.0  
4       1.0         0.0

In [9]:
df_out.to_csv('housing_X_feateng_complete.csv', index=False)
df_target.to_csv('housing_y_feateng_complete.csv', index=False)

$\diamondsuit$

## Appendices

### Feature Engineering - Imputation

In [10]:
imputer1 = SimpleImputer(strategy='median')
df_imputer1 = pd.DataFrame(imputer1.fit_transform(df_numericonly), columns=df_numericonly.columns)

display(df_numericonly.describe())
display(df_imputer1.describe())

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  
count    20433.000000  20640.000000  20640.000000   20640.000000  
mean       537.870553   1425.476744    499.539680       3.870671  
std        421.385070   1132.462122    382.329753       1.899822  
min          1.000000      3.000000      1.000000       0.499900  
25%        296.000000    787.000000    280.000000       2.563400  
50%        435.000000   1166.000000    409.000000       3.534800  
75%        647.000000   1725.000000    605.000000       4.743250  
max       6445.000000  35682.000000   6082.000000      15.000100

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  
count    20640.000000  20640.000000  20640.000000   20640.000000  
mean       536.838857   1425.476744    499.539680       3.870671  
std        419.391878   1132.462122    382.329753       1.899822  
min          1.000000      3.000000      1.000000       0.499900  
25%        297.000000    787.000000    280.000000       2.563400  
50%        435.000000   1166.000000    409.000000       3.534800  
75%        643.250000   1725.000000    605.000000       4.743250  
max       6445.000000  35682.000000   6082.000000      15.000100

### Feature Engineering - Categorical

In [11]:
encoder1 = LabelEncoder()

df_encoder1 = encoder1.fit_transform(df_categoricalonly)
print(encoder1.classes_)

print(len(df_encoder1))
print(df_encoder1[:5])

['<1H OCEAN' 'INLAND' 'ISLAND' 'NEAR BAY' 'NEAR OCEAN']
20640
[3 3 3 3 3]


/Users/bryanlim/.pyenv/versions/3.7.2/envs/interviews/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
encoder2 = OneHotEncoder()
df_encoder2 = encoder2.fit_transform(df_encoder1.reshape(-1,1))

print(df_encoder2.shape)
print(df_encoder2.A[:5])

(20640, 5)
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]


In [13]:
encoder3 = MyLabelBinarizer()
df_encoder3 = encoder3.fit_transform(df_categoricalonly)
print(df_encoder3[:5])

[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]


### Feature Engineering - Scaling

In [14]:
scaler = StandardScaler()
df['households_scale'] = scaler.fit_transform(df[['households']])
print(df[['households_scale', 'households']].describe())

       households_scale    households
count      2.064000e+04  20640.000000
mean       6.885104e-17    499.539680
std        1.000024e+00    382.329753
min       -1.303984e+00      1.000000
25%       -5.742294e-01    280.000000
50%       -2.368162e-01    409.000000
75%        2.758427e-01    605.000000
max        1.460152e+01   6082.000000


### Feature Engineering - Combination

In [15]:
attr_adder = CombinedAttributesAdder()
housing_extra_attribs = attr_adder.transform(df.values)